name: Build & Publish to deploy (Bun + Plesk)

on:
  push:
    branches: [ main ]     # cada push a main publica
  workflow_dispatch:        # también puedes lanzarlo a mano

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # necesario para publicar a otra rama

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Publish dist/ to deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: deploy
          force_orphan: true
